namespace LegatroLight.Dialogs;

partial class FrmUserSetupAssistant
{
    private System.ComponentModel.IContainer components = null;

    protected override void Dispose(bool disposing)
    {
        if (disposing && (components != null))
        {
            components.Dispose();
        }
        base.Dispose(disposing);
    }

    #region Windows Form Designer generated code

    private void InitializeComponent()
    {
        _mainTableLayoutPanel = new TableLayoutPanel();
        _lblTitle = new Label();
        _lblDescription = new Label();
        _formTableLayoutPanel = new TableLayoutPanel();
        _lblUserAuthID = new Label();
        _txtUserAuthID = new TextBox();
        _lblUserSid = new Label();
        _txtUserSid = new TextBox();
        _lblDisplayName = new Label();
        _txtDisplayName = new TextBox();
        _lblUserName = new Label();
        _txtUserName = new TextBox();
        _lblDomainOrMachine = new Label();
        _txtDomainOrMachine = new TextBox();
        _lblNickname = new Label();
        _txtNickname = new TextBox();
        _lblEmail = new Label();
        _txtEmail = new TextBox();
        _lblFirstName = new Label();
        _txtFirstName = new TextBox();
        _lblMiddleName = new Label();
        _txtMiddleName = new TextBox();
        _lblLastName = new Label();
        _txtLastName = new TextBox();
        _buttonFlowLayoutPanel = new FlowLayoutPanel();
        _btnCancel = new Button();
        _btnOK = new Button();
        _mainTableLayoutPanel.SuspendLayout();
        _formTableLayoutPanel.SuspendLayout();
        _buttonFlowLayoutPanel.SuspendLayout();
        SuspendLayout();
        _mainTableLayoutPanel.ColumnCount = 1;
        _mainTableLayoutPanel.ColumnStyles.Add(new ColumnStyle(SizeType.Percent, 100F));
        _mainTableLayoutPanel.Controls.Add(_lblTitle, 0, 0);
        _mainTableLayoutPanel.Controls.Add(_lblDescription, 0, 1);
        _mainTableLayoutPanel.Controls.Add(_formTableLayoutPanel, 0, 2);
        _mainTableLayoutPanel.Controls.Add(_buttonFlowLayoutPanel, 0, 3);
        _mainTableLayoutPanel.Dock = DockStyle.Fill;
        _mainTableLayoutPanel.Location = new Point(0, 0);
        _mainTableLayoutPanel.Name = "_mainTableLayoutPanel";
        _mainTableLayoutPanel.Padding = new Padding(10);
        _mainTableLayoutPanel.RowCount = 4;
        _mainTableLayoutPanel.RowStyles.Add(new RowStyle(SizeType.Absolute, 35F));
        _mainTableLayoutPanel.RowStyles.Add(new RowStyle(SizeType.Absolute, 40F));
        _mainTableLayoutPanel.RowStyles.Add(new RowStyle(SizeType.Percent, 100F));
        _mainTableLayoutPanel.RowStyles.Add(new RowStyle(SizeType.Absolute, 45F));
        _mainTableLayoutPanel.Size = new Size(684, 561);
        _mainTableLayoutPanel.TabIndex = 0;
        _lblTitle.AutoSize = true;
        _lblTitle.Dock = DockStyle.Fill;
        _lblTitle.Font = new Font("Segoe UI", 14F, FontStyle.Bold);
        _lblTitle.Location = new Point(13, 10);
        _lblTitle.Name = "_lblTitle";
        _lblTitle.Size = new Size(658, 35);
        _lblTitle.TabIndex = 0;
        _lblTitle.Text = "User Setup Assistant";
        _lblTitle.TextAlign = ContentAlignment.MiddleLeft;
        _lblDescription.AutoSize = true;
        _lblDescription.Dock = DockStyle.Fill;
        _lblDescription.Location = new Point(13, 45);
        _lblDescription.Name = "_lblDescription";
        _lblDescription.Size = new Size(658, 40);
        _lblDescription.TabIndex = 1;
        _lblDescription.Text = "Welcome! Please review and complete your user information. Required fields are marked with *.";
        _lblDescription.TextAlign = ContentAlignment.MiddleLeft;
        _formTableLayoutPanel.ColumnCount = 2;
        _formTableLayoutPanel.ColumnStyles.Add(new ColumnStyle(SizeType.Absolute, 180F));
        _formTableLayoutPanel.ColumnStyles.Add(new ColumnStyle(SizeType.Percent, 100F));
        _formTableLayoutPanel.Controls.Add(_lblUserAuthID, 0, 0);
        _formTableLayoutPanel.Controls.Add(_txtUserAuthID, 1, 0);
        _formTableLayoutPanel.Controls.Add(_lblUserSid, 0, 1);
        _formTableLayoutPanel.Controls.Add(_txtUserSid, 1, 1);
        _formTableLayoutPanel.Controls.Add(_lblDisplayName, 0, 2);
        _formTableLayoutPanel.Controls.Add(_txtDisplayName, 1, 2);
        _formTableLayoutPanel.Controls.Add(_lblUserName, 0, 3);
        _formTableLayoutPanel.Controls.Add(_txtUserName, 1, 3);
        _formTableLayoutPanel.Controls.Add(_lblDomainOrMachine, 0, 4);
        _formTableLayoutPanel.Controls.Add(_txtDomainOrMachine, 1, 4);
        _formTableLayoutPanel.Controls.Add(_lblNickname, 0, 5);
        _formTableLayoutPanel.Controls.Add(_txtNickname, 1, 5);
        _formTableLayoutPanel.Controls.Add(_lblEmail, 0, 6);
        _formTableLayoutPanel.Controls.Add(_txtEmail, 1, 6);
        _formTableLayoutPanel.Controls.Add(_lblFirstName, 0, 7);
        _formTableLayoutPanel.Controls.Add(_txtFirstName, 1, 7);
        _formTableLayoutPanel.Controls.Add(_lblMiddleName, 0, 8);
        _formTableLayoutPanel.Controls.Add(_txtMiddleName, 1, 8);
        _formTableLayoutPanel.Controls.Add(_lblLastName, 0, 9);
        _formTableLayoutPanel.Controls.Add(_txtLastName, 1, 9);
        _formTableLayoutPanel.Dock = DockStyle.Fill;
        _formTableLayoutPanel.Location = new Point(13, 88);
        _formTableLayoutPanel.Name = "_formTableLayoutPanel";
        _formTableLayoutPanel.RowCount = 10;
        _formTableLayoutPanel.RowStyles.Add(new RowStyle(SizeType.Absolute, 35F));
        _formTableLayoutPanel.RowStyles.Add(new RowStyle(SizeType.Absolute, 35F));
        _formTableLayoutPanel.RowStyles.Add(new RowStyle(SizeType.Absolute, 35F));
        _formTableLayoutPanel.RowStyles.Add(new RowStyle(SizeType.Absolute, 35F));
        _formTableLayoutPanel.RowStyles.Add(new RowStyle(SizeType.Absolute, 35F));
        _formTableLayoutPanel.RowStyles.Add(new RowStyle(SizeType.Absolute, 35F));
        _formTableLayoutPanel.RowStyles.Add(new RowStyle(SizeType.Absolute, 35F));
        _formTableLayoutPanel.RowStyles.Add(new RowStyle(SizeType.Absolute, 35F));
        _formTableLayoutPanel.RowStyles.Add(new RowStyle(SizeType.Absolute, 35F));
        _formTableLayoutPanel.RowStyles.Add(new RowStyle(SizeType.Absolute, 35F));
        _formTableLayoutPanel.Size = new Size(658, 418);
        _formTableLayoutPanel.TabIndex = 2;
        _lblUserAuthID.Anchor = AnchorStyles.Left | AnchorStyles.Right;
        _lblUserAuthID.AutoSize = true;
        _lblUserAuthID.Location = new Point(3, 7);
        _lblUserAuthID.Name = "_lblUserAuthID";
        _lblUserAuthID.Size = new Size(174, 20);
        _lblUserAuthID.TabIndex = 0;
        _lblUserAuthID.Text = "Windows Auth ID:";
        _lblUserAuthID.TextAlign = ContentAlignment.MiddleLeft;
        _txtUserAuthID.Anchor = AnchorStyles.Top | AnchorStyles.Bottom | AnchorStyles.Left | AnchorStyles.Right;
        _txtUserAuthID.Location = new Point(183, 3);
        _txtUserAuthID.Margin = new Padding(3);
        _txtUserAuthID.Name = "_txtUserAuthID";
        _txtUserAuthID.ReadOnly = true;
        _txtUserAuthID.Size = new Size(472, 27);
        _txtUserAuthID.TabIndex = 1;
        _txtUserAuthID.TabStop = false;
        _lblUserSid.Anchor = AnchorStyles.Left | AnchorStyles.Right;
        _lblUserSid.AutoSize = true;
        _lblUserSid.Location = new Point(3, 42);
        _lblUserSid.Name = "_lblUserSid";
        _lblUserSid.Size = new Size(174, 20);
        _lblUserSid.TabIndex = 2;
        _lblUserSid.Text = "User SID:";
        _lblUserSid.TextAlign = ContentAlignment.MiddleLeft;
        _txtUserSid.Anchor = AnchorStyles.Top | AnchorStyles.Bottom | AnchorStyles.Left | AnchorStyles.Right;
        _txtUserSid.Location = new Point(183, 38);
        _txtUserSid.Margin = new Padding(3);
        _txtUserSid.Name = "_txtUserSid";
        _txtUserSid.ReadOnly = true;
        _txtUserSid.Size = new Size(472, 27);
        _txtUserSid.TabIndex = 3;
        _txtUserSid.TabStop = false;
        _lblDisplayName.Anchor = AnchorStyles.Left | AnchorStyles.Right;
        _lblDisplayName.AutoSize = true;
        _lblDisplayName.Location = new Point(3, 77);
        _lblDisplayName.Name = "_lblDisplayName";
        _lblDisplayName.Size = new Size(174, 20);
        _lblDisplayName.TabIndex = 4;
        _lblDisplayName.Text = "Display Name: *";
        _lblDisplayName.TextAlign = ContentAlignment.MiddleLeft;
        _txtDisplayName.Anchor = AnchorStyles.Top | AnchorStyles.Bottom | AnchorStyles.Left | AnchorStyles.Right;
        _txtDisplayName.Location = new Point(183, 73);
        _txtDisplayName.Margin = new Padding(3);
        _txtDisplayName.Name = "_txtDisplayName";
        _txtDisplayName.Size = new Size(472, 27);
        _txtDisplayName.TabIndex = 5;
        _lblUserName.Anchor = AnchorStyles.Left | AnchorStyles.Right;
        _lblUserName.AutoSize = true;
        _lblUserName.Location = new Point(3, 112);
        _lblUserName.Name = "_lblUserName";
        _lblUserName.Size = new Size(174, 20);
        _lblUserName.TabIndex = 6;
        _lblUserName.Text = "User Name:";
        _lblUserName.TextAlign = ContentAlignment.MiddleLeft;
        _txtUserName.Anchor = AnchorStyles.Top | AnchorStyles.Bottom | AnchorStyles.Left | AnchorStyles.Right;
        _txtUserName.Location = new Point(183, 108);
        _txtUserName.Margin = new Padding(3);
        _txtUserName.Name = "_txtUserName";
        _txtUserName.ReadOnly = true;
        _txtUserName.Size = new Size(472, 27);
        _txtUserName.TabIndex = 7;
        _txtUserName.TabStop = false;
        _lblDomainOrMachine.Anchor = AnchorStyles.Left | AnchorStyles.Right;
        _lblDomainOrMachine.AutoSize = true;
        _lblDomainOrMachine.Location = new Point(3, 147);
        _lblDomainOrMachine.Name = "_lblDomainOrMachine";
        _lblDomainOrMachine.Size = new Size(174, 20);
        _lblDomainOrMachine.TabIndex = 8;
        _lblDomainOrMachine.Text = "Domain/Machine:";
        _lblDomainOrMachine.TextAlign = ContentAlignment.MiddleLeft;
        _txtDomainOrMachine.Anchor = AnchorStyles.Top | AnchorStyles.Bottom | AnchorStyles.Left | AnchorStyles.Right;
        _txtDomainOrMachine.Location = new Point(183, 143);
        _txtDomainOrMachine.Margin = new Padding(3);
        _txtDomainOrMachine.Name = "_txtDomainOrMachine";
        _txtDomainOrMachine.ReadOnly = true;
        _txtDomainOrMachine.Size = new Size(472, 27);
        _txtDomainOrMachine.TabIndex = 9;
        _txtDomainOrMachine.TabStop = false;
        _lblNickname.Anchor = AnchorStyles.Left | AnchorStyles.Right;
        _lblNickname.AutoSize = true;
        _lblNickname.Location = new Point(3, 182);
        _lblNickname.Name = "_lblNickname";
        _lblNickname.Size = new Size(174, 20);
        _lblNickname.TabIndex = 10;
        _lblNickname.Text = "Nickname (Display ID): *";
        _lblNickname.TextAlign = ContentAlignment.MiddleLeft;
        _txtNickname.Anchor = AnchorStyles.Top | AnchorStyles.Bottom | AnchorStyles.Left | AnchorStyles.Right;
        _txtNickname.Location = new Point(183, 178);
        _txtNickname.Margin = new Padding(3);
        _txtNickname.Name = "_txtNickname";
        _txtNickname.Size = new Size(472, 27);
        _txtNickname.TabIndex = 11;
        _lblEmail.Anchor = AnchorStyles.Left | AnchorStyles.Right;
        _lblEmail.AutoSize = true;
        _lblEmail.Location = new Point(3, 217);
        _lblEmail.Name = "_lblEmail";
        _lblEmail.Size = new Size(174, 20);
        _lblEmail.TabIndex = 12;
        _lblEmail.Text = "Email:";
        _lblEmail.TextAlign = ContentAlignment.MiddleLeft;
        _txtEmail.Anchor = AnchorStyles.Top | AnchorStyles.Bottom | AnchorStyles.Left | AnchorStyles.Right;
        _txtEmail.Location = new Point(183, 213);
        _txtEmail.Margin = new Padding(3);
        _txtEmail.Name = "_txtEmail";
        _txtEmail.Size = new Size(472, 27);
        _txtEmail.TabIndex = 13;
        _lblFirstName.Anchor = AnchorStyles.Left | AnchorStyles.Right;
        _lblFirstName.AutoSize = true;
        _lblFirstName.Location = new Point(3, 252);
        _lblFirstName.Name = "_lblFirstName";
        _lblFirstName.Size = new Size(174, 20);
        _lblFirstName.TabIndex = 14;
        _lblFirstName.Text = "First Name:";
        _lblFirstName.TextAlign = ContentAlignment.MiddleLeft;
        _txtFirstName.Anchor = AnchorStyles.Top | AnchorStyles.Bottom | AnchorStyles.Left | AnchorStyles.Right;
        _txtFirstName.Location = new Point(183, 248);
        _txtFirstName.Margin = new Padding(3);
        _txtFirstName.Name = "_txtFirstName";
        _txtFirstName.Size = new Size(472, 27);
        _txtFirstName.TabIndex = 15;
        _lblMiddleName.Anchor = AnchorStyles.Left | AnchorStyles.Right;
        _lblMiddleName.AutoSize = true;
        _lblMiddleName.Location = new Point(3, 287);
        _lblMiddleName.Name = "_lblMiddleName";
        _lblMiddleName.Size = new Size(174, 20);
        _lblMiddleName.TabIndex = 16;
        _lblMiddleName.Text = "Middle Name:";
        _lblMiddleName.TextAlign = ContentAlignment.MiddleLeft;
        _txtMiddleName.Anchor = AnchorStyles.Top | AnchorStyles.Bottom | AnchorStyles.Left | AnchorStyles.Right;
        _txtMiddleName.Location = new Point(183, 283);
        _txtMiddleName.Margin = new Padding(3);
        _txtMiddleName.Name = "_txtMiddleName";
        _txtMiddleName.Size = new Size(472, 27);
        _txtMiddleName.TabIndex = 17;
        _lblLastName.Anchor = AnchorStyles.Left | AnchorStyles.Right;
        _lblLastName.AutoSize = true;
        _lblLastName.Location = new Point(3, 322);
        _lblLastName.Name = "_lblLastName";
        _lblLastName.Size = new Size(174, 20);
        _lblLastName.TabIndex = 18;
        _lblLastName.Text = "Last Name:";
        _lblLastName.TextAlign = ContentAlignment.MiddleLeft;
        _txtLastName.Anchor = AnchorStyles.Top | AnchorStyles.Bottom | AnchorStyles.Left | AnchorStyles.Right;
        _txtLastName.Location = new Point(183, 318);
        _txtLastName.Margin = new Padding(3);
        _txtLastName.Name = "_txtLastName";
        _txtLastName.Size = new Size(472, 27);
        _txtLastName.TabIndex = 19;
        _buttonFlowLayoutPanel.AutoSize = true;
        _buttonFlowLayoutPanel.Dock = DockStyle.Fill;
        _buttonFlowLayoutPanel.FlowDirection = FlowDirection.RightToLeft;
        _buttonFlowLayoutPanel.Location = new Point(13, 512);
        _buttonFlowLayoutPanel.Name = "_buttonFlowLayoutPanel";
        _buttonFlowLayoutPanel.Size = new Size(658, 39);
        _buttonFlowLayoutPanel.TabIndex = 3;
        _btnCancel.DialogResult = DialogResult.Cancel;
        _btnCancel.Location = new Point(555, 3);
        _btnCancel.Name = "_btnCancel";
        _btnCancel.Size = new Size(100, 32);
        _btnCancel.TabIndex = 1;
        _btnCancel.Text = "Cancel";
        _btnCancel.UseVisualStyleBackColor = true;
        _btnCancel.Click += BtnCancel_Click;
        _btnOK.Location = new Point(449, 3);
        _btnOK.Name = "_btnOK";
        _btnOK.Size = new Size(100, 32);
        _btnOK.TabIndex = 0;
        _btnOK.Text = "OK";
        _btnOK.UseVisualStyleBackColor = true;
        _btnOK.Click += BtnOK_Click;
        AcceptButton = _btnOK;
        AutoScaleDimensions = new SizeF(8F, 20F);
        AutoScaleMode = AutoScaleMode.Font;
        CancelButton = _btnCancel;
        ClientSize = new Size(684, 561);
        Controls.Add(_mainTableLayoutPanel);
        FormBorderStyle = FormBorderStyle.FixedDialog;
        MaximizeBox = false;
        MinimizeBox = false;
        Name = "FrmUserSetupAssistant";
        StartPosition = FormStartPosition.CenterParent;
        Text = "User Setup Assistant";
        _mainTableLayoutPanel.ResumeLayout(false);
        _mainTableLayoutPanel.PerformLayout();
        _formTableLayoutPanel.ResumeLayout(false);
        _formTableLayoutPanel.PerformLayout();
        _buttonFlowLayoutPanel.ResumeLayout(false);
        ResumeLayout(false);
    }

    #endregion

    private TableLayoutPanel _mainTableLayoutPanel;
    private Label _lblTitle;
    private Label _lblDescription;
    private TableLayoutPanel _formTableLayoutPanel;
    private Label _lblUserAuthID;
    private TextBox _txtUserAuthID;
    private Label _lblUserSid;
    private TextBox _txtUserSid;
    private Label _lblDisplayName;
    private TextBox _txtDisplayName;
    private Label _lblUserName;
    private TextBox _txtUserName;
    private Label _lblDomainOrMachine;
    private TextBox _txtDomainOrMachine;
    private Label _lblNickname;
    private TextBox _txtNickname;
    private Label _lblEmail;
    private TextBox _txtEmail;
    private Label _lblFirstName;
    private TextBox _txtFirstName;
    private Label _lblMiddleName;
    private TextBox _txtMiddleName;
    private Label _lblLastName;
    private TextBox _txtLastName;
    private FlowLayoutPanel _buttonFlowLayoutPanel;
    private Button _btnCancel;
    private Button _btnOK;
}
