// <auto-generated />
using LegatroLight.Data.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace LegatroLight.Migrations
{
    [DbContext(typeof(LegatroDbContext))]
    partial class LegatroDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.10");

            modelBuilder.Entity("LegatroLight.Data.Entities.Category", b =>
                {
                    b.Property<string>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasColumnName("IDCategory");

                    b.Property<string>("BackColor")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("TEXT");

                    b.Property<string>("CategoryName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("TEXT");

                    b.Property<string>("DateCreated")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("DateDeleted")
                        .HasColumnType("TEXT");

                    b.Property<string>("DateLastEdited")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ForeColor")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("TEXT");

                    b.Property<string>("IDSymbol")
                        .HasColumnType("TEXT");

                    b.Property<string>("IDUser")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsSystem")
                        .HasColumnType("INTEGER");

                    b.Property<string>("SyncGuidChanged")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("CategoryName")
                        .HasDatabaseName("IX_Categories_CategoryName");

                    b.HasIndex("DateCreated")
                        .HasDatabaseName("IX_Categories_DateCreated");

                    b.HasIndex("DateDeleted")
                        .HasDatabaseName("IX_Categories_DateDeleted");

                    b.HasIndex("IDSymbol")
                        .HasDatabaseName("IX_Categories_IDSymbol");

                    b.HasIndex("IDUser")
                        .HasDatabaseName("IX_Categories_IDUser");

                    b.ToTable("Categories", (string)null);
                });

            modelBuilder.Entity("LegatroLight.Data.Entities.Group", b =>
                {
                    b.Property<string>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasColumnName("IDGroup");

                    b.Property<int?>("AutoRangeOffset")
                        .HasColumnType("INTEGER");

                    b.Property<string>("AutoRangeSpan")
                        .HasColumnType("TEXT");

                    b.Property<string>("BackColor")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("TEXT");

                    b.Property<string>("CreatedByIDUser")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("DateCreated")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("DateDeleted")
                        .HasColumnType("TEXT");

                    b.Property<string>("DateLastEdited")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ForeColor")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("TEXT");

                    b.Property<string>("GroupDescription")
                        .HasMaxLength(4000)
                        .HasColumnType("TEXT");

                    b.Property<string>("GroupDisplayName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("TEXT");

                    b.Property<string>("IDSymbol")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsHidden")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsSystem")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("OrderNo")
                        .HasColumnType("INTEGER");

                    b.Property<string>("SyncGuidChanged")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("CreatedByIDUser")
                        .HasDatabaseName("IX_Groups_CreatedByIDUser");

                    b.HasIndex("DateCreated")
                        .HasDatabaseName("IX_Groups_DateCreated");

                    b.HasIndex("DateDeleted")
                        .HasDatabaseName("IX_Groups_DateDeleted");

                    b.HasIndex("GroupDisplayName")
                        .HasDatabaseName("IX_Groups_GroupDisplayName");

                    b.HasIndex("IDSymbol")
                        .HasDatabaseName("IX_Groups_IDSymbol");

                    b.HasIndex("OrderNo")
                        .HasDatabaseName("IX_Groups_OrderNo");

                    b.ToTable("Groups", (string)null);
                });

            modelBuilder.Entity("LegatroLight.Data.Entities.Project", b =>
                {
                    b.Property<string>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasColumnName("IDProject");

                    b.Property<string>("DateCreated")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("DateDeleted")
                        .HasColumnType("TEXT");

                    b.Property<string>("DateLastEdited")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .HasMaxLength(4000)
                        .HasColumnType("TEXT");

                    b.Property<string>("DueDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("IDCategory")
                        .HasColumnType("TEXT");

                    b.Property<string>("IDUser")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsSystem")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ProjectName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("TEXT");

                    b.Property<string>("SyncGuidChanged")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("TimeBudget")
                        .HasColumnType("TEXT");

                    b.Property<string>("TimeSpent")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasDefaultValue("00:00:00");

                    b.HasKey("Id");

                    b.HasIndex("DateCreated")
                        .HasDatabaseName("IX_Projects_DateCreated");

                    b.HasIndex("DateDeleted")
                        .HasDatabaseName("IX_Projects_DateDeleted");

                    b.HasIndex("DueDate")
                        .HasDatabaseName("IX_Projects_DueDate");

                    b.HasIndex("IDCategory")
                        .HasDatabaseName("IX_Projects_IDCategory");

                    b.HasIndex("IDUser")
                        .HasDatabaseName("IX_Projects_IDUser");

                    b.HasIndex("ProjectName")
                        .HasDatabaseName("IX_Projects_ProjectName");

                    b.ToTable("Projects", (string)null);
                });

            modelBuilder.Entity("LegatroLight.Data.Entities.SymbolConfiguration", b =>
                {
                    b.Property<string>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasColumnName("IDSymbol");

                    b.Property<double>("ContrastRatio")
                        .HasColumnType("REAL");

                    b.Property<string>("DateCreated")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("DateDeleted")
                        .HasColumnType("TEXT");

                    b.Property<string>("DateLastEdited")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("DefaultBackColor")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("TEXT");

                    b.Property<string>("DefaultForeColor")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsSystem")
                        .HasColumnType("INTEGER");

                    b.Property<string>("SymbolChar")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("TEXT");

                    b.Property<string>("SymbolName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("TEXT");

                    b.Property<string>("SyncGuidChanged")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("DateCreated")
                        .HasDatabaseName("IX_SymbolConfiguration_DateCreated");

                    b.HasIndex("DateDeleted")
                        .HasDatabaseName("IX_SymbolConfiguration_DateDeleted");

                    b.HasIndex("IsSystem")
                        .HasDatabaseName("IX_SymbolConfiguration_IsSystem");

                    b.HasIndex("SymbolChar")
                        .IsUnique()
                        .HasDatabaseName("IX_SymbolConfiguration_SymbolChar");

                    b.HasIndex("SymbolName")
                        .IsUnique()
                        .HasDatabaseName("IX_SymbolConfiguration_SymbolName");

                    b.ToTable("SymbolConfigurations", (string)null);
                });

            modelBuilder.Entity("LegatroLight.Data.Entities.TimeEntry", b =>
                {
                    b.Property<string>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasColumnName("IDTimeEntry");

                    b.Property<string>("DateCreated")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("DateDeleted")
                        .HasColumnType("TEXT");

                    b.Property<string>("DateLastEdited")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("DescriptionDoneWork")
                        .HasMaxLength(1000)
                        .HasColumnType("TEXT");

                    b.Property<string>("Duration")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("EndTime")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("IDProject")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("IDTodoTask")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("IDUser")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("StartTime")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("SyncGuidChanged")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("TimeZone")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("DateDeleted")
                        .HasDatabaseName("IX_TimeEntries_DateDeleted");

                    b.HasIndex("EndTime")
                        .HasDatabaseName("IX_TimeEntries_EndTime");

                    b.HasIndex("IDProject")
                        .HasDatabaseName("IX_TimeEntries_IDProject");

                    b.HasIndex("IDTodoTask")
                        .HasDatabaseName("IX_TimeEntries_IDTodoTask");

                    b.HasIndex("IDUser")
                        .HasDatabaseName("IX_TimeEntries_IDUser");

                    b.HasIndex("StartTime")
                        .HasDatabaseName("IX_TimeEntries_StartTime");

                    b.ToTable("TimeEntries", (string)null);
                });

            modelBuilder.Entity("LegatroLight.Data.Entities.TodoTask", b =>
                {
                    b.Property<string>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasColumnName("IDTodoTask");

                    b.Property<string>("DateCreated")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("DateDeleted")
                        .HasColumnType("TEXT");

                    b.Property<string>("DateFinished")
                        .HasColumnType("TEXT");

                    b.Property<string>("DateLastEdited")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .HasMaxLength(4000)
                        .HasColumnType("TEXT");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("TEXT");

                    b.Property<string>("DueDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("EstimatedEffort")
                        .HasColumnType("TEXT");

                    b.Property<string>("IDProject")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("IDUser")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("PercentDone")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(0);

                    b.Property<int>("Priority")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(3);

                    b.Property<string>("SyncGuidChanged")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("TimeSpent")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasDefaultValue("00:00:00");

                    b.HasKey("Id");

                    b.HasIndex("DateCreated")
                        .HasDatabaseName("IX_TodoTasks_DateCreated");

                    b.HasIndex("DateDeleted")
                        .HasDatabaseName("IX_TodoTasks_DateDeleted");

                    b.HasIndex("DateFinished")
                        .HasDatabaseName("IX_TodoTasks_DateFinished");

                    b.HasIndex("DisplayName")
                        .HasDatabaseName("IX_TodoTasks_DisplayName");

                    b.HasIndex("DueDate")
                        .HasDatabaseName("IX_TodoTasks_DueDate");

                    b.HasIndex("IDProject")
                        .HasDatabaseName("IX_TodoTasks_IDProject");

                    b.HasIndex("IDUser")
                        .HasDatabaseName("IX_TodoTasks_IDUser");

                    b.HasIndex("Priority")
                        .HasDatabaseName("IX_TodoTasks_Priority");

                    b.ToTable("TodoTasks", (string)null);
                });

            modelBuilder.Entity("LegatroLight.Data.Entities.TodoTasksGroupsRelation", b =>
                {
                    b.Property<string>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasColumnName("IDTodoTasksGroups");

                    b.Property<string>("DateCreated")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("DateDeleted")
                        .HasColumnType("TEXT");

                    b.Property<string>("DateLastEdited")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("IDGroup")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("IDTodoTask")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("IDUser")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("SyncGuidChanged")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("DateDeleted")
                        .HasDatabaseName("IX_TodoTasksGroupsRelations_DateDeleted");

                    b.HasIndex("IDGroup")
                        .HasDatabaseName("IX_TodoTasksGroupsRelations_IDGroup");

                    b.HasIndex("IDTodoTask")
                        .HasDatabaseName("IX_TodoTasksGroupsRelations_IDTodoTask");

                    b.HasIndex("IDUser")
                        .HasDatabaseName("IX_TodoTasksGroupsRelations_IDUser");

                    b.HasIndex("IDTodoTask", "IDGroup")
                        .IsUnique()
                        .HasDatabaseName("IX_TodoTasksGroupsRelations_Composite");

                    b.ToTable("TodoTasksGroupsRelations", (string)null);
                });

            modelBuilder.Entity("LegatroLight.Data.Entities.User", b =>
                {
                    b.Property<string>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasColumnName("IDUser");

                    b.Property<string>("DateCreated")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("DateDeleted")
                        .HasColumnType("TEXT");

                    b.Property<string>("DateLastEdited")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("TEXT");

                    b.Property<string>("DomainOrMachine")
                        .HasMaxLength(255)
                        .HasColumnType("TEXT");

                    b.Property<string>("Email")
                        .HasMaxLength(255)
                        .HasColumnType("TEXT");

                    b.Property<string>("FirstName")
                        .HasMaxLength(255)
                        .HasColumnType("TEXT");

                    b.Property<string>("LastName")
                        .HasMaxLength(255)
                        .HasColumnType("TEXT");

                    b.Property<string>("MiddleName")
                        .HasMaxLength(255)
                        .HasColumnType("TEXT");

                    b.Property<string>("SyncGuidChanged")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("UserAuthID")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("TEXT");

                    b.Property<string>("UserDisplayId")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("TEXT");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("TEXT");

                    b.Property<string>("UserSid")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("DateCreated")
                        .HasDatabaseName("IX_Users_DateCreated");

                    b.HasIndex("DateDeleted")
                        .HasDatabaseName("IX_Users_DateDeleted");

                    b.HasIndex("UserAuthID")
                        .IsUnique()
                        .HasDatabaseName("IX_Users_UserAuthID");

                    b.HasIndex("UserDisplayId")
                        .IsUnique()
                        .HasDatabaseName("IX_Users_UserDisplayId");

                    b.HasIndex("UserSid")
                        .IsUnique()
                        .HasDatabaseName("IX_Users_UserSid");

                    b.ToTable("Users", (string)null);
                });

            modelBuilder.Entity("LegatroLight.Data.Entities.Category", b =>
                {
                    b.HasOne("LegatroLight.Data.Entities.SymbolConfiguration", "Symbol")
                        .WithMany("Categories")
                        .HasForeignKey("IDSymbol")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("LegatroLight.Data.Entities.User", "User")
                        .WithMany("Categories")
                        .HasForeignKey("IDUser")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Symbol");

                    b.Navigation("User");
                });

            modelBuilder.Entity("LegatroLight.Data.Entities.Group", b =>
                {
                    b.HasOne("LegatroLight.Data.Entities.User", "CreatedByUser")
                        .WithMany("Groups")
                        .HasForeignKey("CreatedByIDUser")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("LegatroLight.Data.Entities.SymbolConfiguration", "Symbol")
                        .WithMany("Groups")
                        .HasForeignKey("IDSymbol")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("CreatedByUser");

                    b.Navigation("Symbol");
                });

            modelBuilder.Entity("LegatroLight.Data.Entities.Project", b =>
                {
                    b.HasOne("LegatroLight.Data.Entities.Category", "Category")
                        .WithMany("Projects")
                        .HasForeignKey("IDCategory")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("LegatroLight.Data.Entities.User", "User")
                        .WithMany("Projects")
                        .HasForeignKey("IDUser")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Category");

                    b.Navigation("User");
                });

            modelBuilder.Entity("LegatroLight.Data.Entities.TimeEntry", b =>
                {
                    b.HasOne("LegatroLight.Data.Entities.Project", "Project")
                        .WithMany("TimeEntries")
                        .HasForeignKey("IDProject")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("LegatroLight.Data.Entities.TodoTask", "TodoTask")
                        .WithMany("TimeEntries")
                        .HasForeignKey("IDTodoTask")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("LegatroLight.Data.Entities.User", "User")
                        .WithMany("TimeEntries")
                        .HasForeignKey("IDUser")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Project");

                    b.Navigation("TodoTask");

                    b.Navigation("User");
                });

            modelBuilder.Entity("LegatroLight.Data.Entities.TodoTask", b =>
                {
                    b.HasOne("LegatroLight.Data.Entities.Project", "Project")
                        .WithMany("TodoTasks")
                        .HasForeignKey("IDProject")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("LegatroLight.Data.Entities.User", "User")
                        .WithMany("TodoTasks")
                        .HasForeignKey("IDUser")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Project");

                    b.Navigation("User");
                });

            modelBuilder.Entity("LegatroLight.Data.Entities.TodoTasksGroupsRelation", b =>
                {
                    b.HasOne("LegatroLight.Data.Entities.Group", "Group")
                        .WithMany("TaskRelations")
                        .HasForeignKey("IDGroup")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("LegatroLight.Data.Entities.TodoTask", "TodoTask")
                        .WithMany("GroupRelations")
                        .HasForeignKey("IDTodoTask")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("LegatroLight.Data.Entities.User", "User")
                        .WithMany()
                        .HasForeignKey("IDUser")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Group");

                    b.Navigation("TodoTask");

                    b.Navigation("User");
                });

            modelBuilder.Entity("LegatroLight.Data.Entities.Category", b =>
                {
                    b.Navigation("Projects");
                });

            modelBuilder.Entity("LegatroLight.Data.Entities.Group", b =>
                {
                    b.Navigation("TaskRelations");
                });

            modelBuilder.Entity("LegatroLight.Data.Entities.Project", b =>
                {
                    b.Navigation("TimeEntries");

                    b.Navigation("TodoTasks");
                });

            modelBuilder.Entity("LegatroLight.Data.Entities.SymbolConfiguration", b =>
                {
                    b.Navigation("Categories");

                    b.Navigation("Groups");
                });

            modelBuilder.Entity("LegatroLight.Data.Entities.TodoTask", b =>
                {
                    b.Navigation("GroupRelations");

                    b.Navigation("TimeEntries");
                });

            modelBuilder.Entity("LegatroLight.Data.Entities.User", b =>
                {
                    b.Navigation("Categories");

                    b.Navigation("Groups");

                    b.Navigation("Projects");

                    b.Navigation("TimeEntries");

                    b.Navigation("TodoTasks");
                });
#pragma warning restore 612, 618
        }
    }
}
